This is the codes for the simulated data for this project
- Survey data
- Assessment Data
- Admission Data
- Teachers Info Data
- Subjects Data
- Student info Data : This was generated with chatgpt but cleaning process was carried out for the final data

## Import the neccessary libraries

In [ ]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm
import seaborn as sns


print("All libraries have been imported!")

All libraries have been imported!

## Print the version of the dependencies.

In [ ]:
print(f"numpy version: {np.__version__}")
print(f"pandas version: {pd.__version__}")
import matplotlib
print(f"matplotlib version: {matplotlib.__version__}")

import scipy
print(f"scipy version: {scipy.__version__}")

import warnings
warnings.filterwarnings("ignore")

numpy version: 1.26.4
pandas version: 2.2.2
matplotlib version: 3.7.1
scipy version: 1.13.1

<a id='survey'></a>
#### Generate Survey Data

In [ ]:
# For reproducibility
np.random.seed(42)

# The total number of students in SS3 class.
num_records = 300

# Sample options for dataset columns.
genders = ['Female', 'Male']
departments = ['Arts', 'Science', 'Business']
home_languages = ['Native', 'English']
english_fluency = ['Not Fluent', 'Fluent', 'Very Fluent']
income_levels = ['Low Income', 'Middle Income', 'High Income']
education_levels = ['No Formal Education', 'Primary Education', 'Secondary Education' ,'Tertiary Education']
disabilities = ['Yes', 'No']
internet_access = ['Yes', 'No']
private_lessons = ['Yes', 'No']
extracurricular_activity = ['Yes', 'No']
resources_access = ['No access', 'Limited access', 'Adequate access', 'Full access']
disciplinary_actions = ['Yes', 'No']
class_participation = ['Rarely', 'Frequently']

# Parameters for the Age distribution.
age_mean = 17.0
age_std_dev = 1.23

# Generate random age values from a normal distribution.
random_age_values = norm.rvs(loc=age_mean, scale=age_std_dev, size=num_records)

# Create a DataFrame for Age.
education_df = pd.DataFrame(random_age_values, columns=['Age'])

# Round the values to get integer ages.
education_df['Age'] = education_df['Age'].round().astype(int)

# Ensure that no age value is less than 15.
education_df['Age'] = education_df['Age'].apply(lambda x: max(x, 15))

# Define the Gender proportion.
gender_proportions = {'Female': 0.590139, 'Male': 0.409861}
disability_proportions = {'Yes': 0.1, 'No': 0.9}

# Generate random gender values based on the given proportions.
education_df['Gender'] = np.random.choice(genders, size=num_records, p=[gender_proportions['Female'], gender_proportions['Male']])

# Define the Department proportion.
department_proportions = {'Science': 0.45, 'Business': 0.22, "Arts":0.33}

# Generate random department values based on the given proportions.
education_df['Department'] = np.random.choice(departments, size=num_records, p=[department_proportions["Arts"], department_proportions["Science"], department_proportions["Business"]])

# Generate other categorical data.
education_df['Home Language'] = np.random.choice(home_languages, size=num_records)
education_df['English Fluency'] = np.random.choice(english_fluency, size=num_records)
education_df['Parents Income'] = np.random.choice(income_levels, size=num_records)
education_df['Parents Highest Education Level'] = np.random.choice(education_levels, size=num_records)
education_df['Attendance Rate'] = np.round(np.random.uniform(50, 100, size=num_records)).astype(int)
education_df['Disability'] = np.random.choice(disabilities, size=num_records, p=[disability_proportions['Yes'], disability_proportions['No']])
education_df['Internet Access'] = np.random.choice(internet_access, size=num_records)
education_df['Private Lessons'] = np.random.choice(private_lessons, size=num_records)
education_df['Extracurricular Activity'] = np.random.choice(extracurricular_activity, size=num_records)
education_df['Resources Access'] = np.random.choice(resources_access, size=num_records)
education_df['Disciplinary Actions'] = np.random.choice(disciplinary_actions, size=num_records)
education_df['Class Participation'] = np.random.choice(class_participation, size=num_records)

# Add a unique student ID for each record.
education_df.insert(0, 'student_id', range(1, num_records + 1))

education_df.head()

,student_id,Age,Gender,Department,Home Language,English Fluency,Parents Income,Parents Highest Education Level,Attendance Rate,Disability,Internet Access,Private Lessons,Extracurricular Activity,Resources Access,Disciplinary Actions,Class Participation
0,1,18,Female,Science,Native,Not Fluent,High Income,Secondary Education,74,No,Yes,No,No,Limited access,Yes,Rarely
1,2,17,Female,Arts,English,Fluent,High Income,Tertiary Education,80,No,Yes,No,No,Adequate access,Yes,Frequently
2,3,18,Male,Science,English,Not Fluent,Low Income,Primary Education,88,No,Yes,No,No,Adequate access,No,Frequently
3,4,19,Male,Arts,Native,Fluent,High Income,Secondary Education,59,No,Yes,Yes,No,Full access,Yes,Frequently
4,5,17,Male,Arts,Native,Not Fluent,Low Income,No Formal Education,75,No,No,Yes,No,Full access,No,Rarely

<a id='Assessment'></a>
#### Assessment Data

#### Define means and Standard Deviations for the general subjects and specific subjects for each departments
to generate the assessment scores we focused on 9 subjects because most external exams in Nigeria require registration of 9 subjects.

In [ ]:
# Define means and standard deviations for general subjects.
general_subject_params = {
    'Maths': {'mean': 55, 'std': 9},
    'English': {'mean': 60, 'std': 10},
    'Civic_education': {'mean': 75, 'std': 8},
    'Economics': {'mean': 70, 'std': 8.5},
}

# Define means and standard deviations for specialized Science subjects.
science_subject_params = {
    'Biology': {'mean': 66, 'std': 10},
    'Chemistry': {'mean': 59, 'std': 14},
    'Physics': {'mean': 61, 'std': 12},
    'Geography': {'mean': 65, 'std': 11.5},
    'Agric': {'mean': 60, 'std': 8},
}

# Define means and standard deviations for specialized Arts subjects.
arts_subject_params = {
    'Lit_in_Eng': {'mean': 59, 'std': 10},
    'Government': {'mean': 59, 'std': 9},
    'CRS': {'mean': 70, 'std': 6},
    'Yoruba': {'mean': 63, 'std': 12},
    'History': {'mean': 55, 'std': 7},
}

# Define means and standard deviations for specialized Business subjects.
business_subject_params = {
    'Government': {'mean': 59, 'std': 9},
    'CRS': {'mean': 70, 'std': 6},
    'Accounting': {'mean': 64, 'std': 10},
    'Commerce': {'mean': 66, 'std': 9},
    'Marketing': {'mean': 68, 'std': 7},
}

### Define the Function to generate Assessment scores data For each Department.

In [ ]:
# Function to generate scores for general and specialized subjects for any department
def generate_department_scores(department, general_subjects, department_subjects):
    """
    Parameters:
    - department: The department for which to generate scores
    - general_subjects: Dictionary of general subjects (mean, std)
    - department_subjects: Dictionary of specialized subjects (mean, std)

    Returns:
    - DataFrame with scores for the specified department
    """
    # Filter the main DataFrame for the specified department
    dept_df = education_df[education_df['Department'] == department].copy()

    # Generate general subject scores for all students in the department
    for subject, params in general_subjects.items():
        score = norm.rvs(loc=params['mean'], scale=params['std'], size=len(dept_df)).clip(0, 97).round()

        # Adjust scores based on additional factors
        for i in range(len(dept_df)):
            if dept_df.iloc[i]['Resources Access'] in ['Adequate access', 'Full access']:
                score[i] += 5
            elif dept_df.iloc[i]['Resources Access'] not in ['Adequate access', 'Full access']:
                score[i] -= 7
            if dept_df.iloc[i]['Class Participation'] == 'Frequently':
                score[i] += 5
            elif dept_df.iloc[i]['Class Participation'] != 'Frequently':
                score[i] -= 8
            if dept_df.iloc[i]['Extracurricular Activity'] == 'Yes':
                score[i] += 5
            elif dept_df.iloc[i]['Extracurricular Activity'] == 'No':
                score[i] -= 8
            if dept_df.iloc[i]['Private Lessons'] == 'Yes':
                score[i] += 5
            elif dept_df.iloc[i]['Private Lessons'] == 'No':
                score[i] -= 8

        dept_df[subject] = score.clip(0, 93).round()

    # Generate specialized subject scores for all students in the department
    for subject, params in department_subjects.items():
        score = norm.rvs(loc=params['mean'], scale=params['std'], size=len(dept_df)).clip(0, 97).round()

        # Adjust scores based on additional factors
        for i in range(len(dept_df)):
            if dept_df.iloc[i]['Resources Access'] in ['Adequate access', 'Full access']:
                score[i] += 5
            elif dept_df.iloc[i]['Resources Access'] not in ['Adequate access', 'Full access']:
                score[i] -= 7
            if dept_df.iloc[i]['Class Participation'] == 'Frequently':
                score[i] += 5
            elif dept_df.iloc[i]['Class Participation'] != 'Frequently':
                score[i] -= 8
            if dept_df.iloc[i]['Extracurricular Activity'] == 'Yes':
                score[i] += 5
            elif dept_df.iloc[i]['Extracurricular Activity'] == 'No':
                score[i] -= 8
            if dept_df.iloc[i]['Private Lessons'] == 'Yes':
                score[i] += 5
            elif dept_df.iloc[i]['Private Lessons'] == 'No':
                score[i] -= 8

        dept_df[subject] = score.clip(0, 95).round()

    return dept_df

### Define function to calculate the Total Grade Point and Average Grade point

In [ ]:
# Function to calculate total grade points and average score for a given DataFrame.
def calculate_grade_points_and_average_score(df, subject_columns):
    # Calculate total grade points.
    df['Total_Grade_Points'] = df[subject_columns].sum(axis=1)

    # Calculate average score.
    df['Average_Score'] = df['Total_Grade_Points'] / len(subject_columns)

    # Retain only the desired columns.
    final_df = df[['student_id'] + subject_columns + ['Total_Grade_Points', 'Average_Score']]
    return final_df



### Generate scores for Students in the Science Department.

In [ ]:
# For reproducibility.
np.random.seed(42)

# Define Subject columns for Science department.
science_subject_columns = ['Maths', 'English', 'Civic_education',
                           'Economics', 'Biology', 'Chemistry',
                           'Physics', 'Geography', 'Agric']

science_df = generate_department_scores('Science', general_subject_params, science_subject_params)

science_df = calculate_grade_points_and_average_score(science_df, science_subject_columns)

science_df.head()

,student_id,Maths,English,Civic_education,Economics,Biology,Chemistry,Physics,Geography,Agric,Total_Grade_Points,Average_Score
0,1,28.0,17.0,45.0,40.0,30.0,24.0,30.0,26.0,36.0,276.0,30.666667
2,3,48.0,56.0,66.0,74.0,56.0,58.0,58.0,54.0,58.0,528.0,58.666667
5,6,56.0,68.0,71.0,66.0,65.0,36.0,75.0,38.0,56.0,531.0,59.000000
6,7,51.0,26.0,62.0,70.0,44.0,54.0,31.0,42.0,45.0,425.0,47.222222
9,10,61.0,70.0,93.0,93.0,77.0,64.0,81.0,45.0,87.0,671.0,74.555556

### Generate scores for Students in the Arts Department.

In [ ]:
# For reproducibility.
np.random.seed(42)

# Define Subject columns for Arts department.
arts_subject_columns = ['Maths', 'English', 'Civic_education',
                        'Economics', 'Lit_in_Eng', 'Government',
                        'CRS', 'Yoruba', 'History']

# generate scores for science students.
arts_df = generate_department_scores('Arts', general_subject_params, arts_subject_params)

arts_df = calculate_grade_points_and_average_score(arts_df, arts_subject_columns)

arts_df.head()

,student_id,Maths,English,Civic_education,Economics,Lit_in_Eng,Government,CRS,Yoruba,History,Total_Grade_Points,Average_Score
1,2,53.0,46.0,73.0,62.0,38.0,60.0,67.0,36.0,46.0,481.0,53.444444
3,4,61.0,65.0,86.0,75.0,79.0,71.0,78.0,54.0,72.0,641.0,71.222222
4,5,55.0,58.0,73.0,73.0,56.0,44.0,59.0,66.0,60.0,544.0,60.444444
7,8,77.0,87.0,93.0,85.0,60.0,68.0,81.0,73.0,59.0,683.0,75.888889
8,9,47.0,56.0,74.0,71.0,69.0,60.0,75.0,55.0,46.0,553.0,61.444444

### Generate scores for Students in the Business Department.

In [ ]:
# For reproducibility.
np.random.seed(42)

# Define Subject columns for Business department.
business_subject_columns = ['Maths', 'English', 'Civic_education',
                           'Economics', 'Government', 'CRS',
                            'Accounting', 'Commerce', 'Marketing']

 # generate business department scores.
business_df = generate_department_scores('Business', general_subject_params, business_subject_params)

#
business_df = calculate_grade_points_and_average_score(business_df, business_subject_columns)

business_df.head()

,student_id,Maths,English,Civic_education,Economics,Government,CRS,Accounting,Commerce,Marketing,Total_Grade_Points,Average_Score
19,20,53.0,57.0,69.0,66.0,53.0,63.0,51.0,50.0,61.0,523.0,58.111111
21,22,36.0,52.0,48.0,59.0,35.0,49.0,44.0,47.0,48.0,418.0,46.444444
29,30,68.0,62.0,91.0,77.0,85.0,73.0,74.0,74.0,79.0,683.0,75.888889
30,31,76.0,65.0,88.0,89.0,72.0,82.0,86.0,78.0,80.0,716.0,79.555556
31,32,48.0,44.0,76.0,63.0,36.0,67.0,68.0,67.0,59.0,528.0,58.666667

#### Generate Admission Data

In [ ]:
np.random.seed(42)
# Constants
num_rows = 300
constant_admission_date = "2022-09-10"  # Constant admission date
admission_years = ["2022"] * 295 + ["2023"] * 5  # 295 for 2022 and 5 for 2023
student_ids = list(range(1, 301))  # Example student IDs from 1 to 300
class_ids = list(range(1, 4))  # Class IDs (for ss3 science, ss3 arts, ss3 business)

# Randomly shuffle student_ids to simulate a random assignment to admissions
random.shuffle(student_ids)

# Generate admission data
data = {
    'admission_id': list(range(1, num_rows + 1)),  # Admission IDs from 1 to 300
    'admission_date': [constant_admission_date] * 290 + ["2023-09-15"] * 10,  # Admission dates
    'admission_year': admission_years,  # Academic years
    'student_id': student_ids,  # Shuffled student IDs
    'class_id': [random.choice(class_ids) for _ in range(num_rows)]  # Randomly assign class IDs
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv('admission_data.csv', index=False)

#### Generate Teacher Info Data

In [ ]:
from datetime import datetime, timedelta
from datetime import datetime, timedelta

def random_start_date():
    two_years_ago = datetime.today() - timedelta(days=730)  # 2 years ago
    # Create a random date between 2 and 4 years ago
    four_years_ago = datetime.today() - timedelta(days=1460)  # 4 years ago
    return four_years_ago + (two_years_ago - four_years_ago) * random.random()

# Sample data for names, addresses, qualifications, and marital status
first_names = [
    "Amina", "Tunde", "Ngozi", "Chinedu", "Kemi", "Emeka", "Zainab",
    "Seyi", "Chuka", "Ifeoma", "Adaeze", "Uche", "Damilola", "Oluwaseun",
    "Tola", "Tosin", "Funmi", "Olumide", "Ayodele", "Adebayo", "Omolara",
    "Nneka", "Ogechi", "Ibrahim", "Sola", "Kehinde", "Titi"
]

last_names = [
    "Kayode", "Adesina", "Chukwu", "Obi", "Osunba", "Nwosu", "Agboola",
    "Yinusa", "Balogun", "Arowosegbe", "Oluwafemi", "Chukwuma", "Adeola",
    "Osagie", "Emenike", "Eze", "Okeowo", "Nnamdi", "Ogbaji", "Dike",
    "Ugochukwu", "Nwafor", "Akintola", "Jibola", "Yusuf", "Oyekunle",
    "Popoola"
]

addresses = [
    "123 Street Name, Lagos", "456 Another St, Abuja",
    "789 Some Ave, Lagos", "1010 New Rd, Ibadan",
    "2020 Old Lane, Kano", "3030 Random St, Enugu",
    "4040 surulere, Lagos", "5050 Example Rd, Jos",
    "6060 Sample St, Akure", "7070 Test Rd, Benin"
]

qualifications = [
    "B.Sc.", "NCE", "HND", "B.Ed."
]

marital_status = ["Single", "Married"]

# Generate sample teacher data
data = {
    'teacher_id': list(range(1, 28)),  # Teacher IDs from 1 to 27
    'employment_id': list(range(1001, 1028)),  # Employment IDs from 1001 to 1027
    'first_name': random.sample(first_names, 27),  # Randomly sampled first names
    'last_name': random.sample(last_names, 27),  # Randomly sampled last names
    'address': random.choices(addresses, k=27),  # Randomly selected addresses
    'phone_number': [f"0{random.randint(701234567, 799999999)}" for _ in range(27)],  # Random phone numbers
    'marital_status': [random.choice(marital_status) for _ in range(27)],  # Random marital status
    'qualification': [random.choice(qualifications) for _ in range(27)],  # Random qualifications
   'start_date': [random_start_date().date() for _ in range(27)]  # Random start dates at least 2 years ago
}

# Create DataFrame
df= pd.DataFrame(data)

# Save to CSV
df.to_csv('teacher_data.csv', index=False)

Generate Subject data

In [ ]:
import pandas as pd
import random
from datetime import datetime, timedelta

# Sample teacher IDs (assuming teacher IDs are 1 to 27)
teacher_ids = list(range(1, 28))

# Define subjects for each department
science_subjects = [
    "Mathathematics", "English", "Civic Education",
    "Economics", "Biology", "Chemistry",
    "Physics", "Geography", "Agric"
]

arts_subjects = [
    "Mathathematics", "English", "Civic Education",
    "Economics", "Government", "CRS",
    "Lit-in-English", "Yoruba", "History"
]

business_subjects = [
    "Mathathematics", "English", "Civic Education",
    "Economics", "Government", "CRS",
    "Accounting", "Commerce", "Marketing"
]

# Create a list for all subjects with their respective departments
subjects = []
for subject in science_subjects:
    subjects.append((subject, "Science"))
for subject in arts_subjects:
    subjects.append((subject, "Arts"))
for subject in business_subjects:
    subjects.append((subject, "Business"))

# Shuffle teacher_ids to ensure randomness
random.shuffle(teacher_ids)

# Ensure each teacher gets a distinct set of subjects
assigned_teacher_ids = []
for i in range(len(subjects)):
    assigned_teacher_ids.append(teacher_ids[i % len(teacher_ids)])

# Generate random subject data
data = {
    'subject_id': list(range(1, len(subjects) + 1)),  # Subject IDs from 1 to number of subjects
    'name': [subject[0] for subject in subjects],  # Subject names
    'teacher_id': assigned_teacher_ids,  # Distinct teacher IDs
    'last_update': [datetime.today() - timedelta(days=random.randint(1, 365)) for _ in range(len(subjects))]  # Random last update dates
}

# Create DataFrame
df = pd.DataFrame(data)

# Convert 'last_update' to date format
df['last_update'] = df['last_update'].dt.date

# Save to CSV
df.to_csv('subject_data.csv', index=False)